students=('Ajith' 'Vinoth' 'Vidya' 'Anu')
echo "***************CREATE*****************"
echo "Before Add"
echo "${students[@]}"
echo "After Add"
students[4]="Nandha"
echo "${students[@]}"
echo "**************RETRIEVE****************"
echo "${students[@]}"
echo "Retrive Based On Index Number"
echo "${students[3]}"
echo "**************UPDATE******************"
echo "Before Update"
echo "${students[@]}"
echo "After Update"
students[1]="Pranith"
echo "${students[@]}"
echo "**************DELETE******************"
echo "Before Delete"
echo "${students[@]}"
unset 'students[4]'
echo "After Delete"
echo "${students[@]}"
echo "***************************************"
echo "*****Display Only Index Numbers********"
echo "${students[@]}"
echo "${!students[@]}"
echo "***Display HeadCount Of An Array*******"
echo "${students[@]}"
echo "${#students[@]}"